// +build autogen

// Package dockerversion is auto-generated at build-time
package dockerversion

// Default build-time variable for library-import.
// This file is overridden on build with build-time information.
const (
	GitCommit             string = "e881a56a8c"
	Version               string = "dev"
	BuildTime             string = ""
	IAmStatic             string = "true"
	PlatformName          string = ""
	ProductName           string = ""
	DefaultProductLicense string = ""
)

// AUTOGENERATED FILE; see /go/src/github.com/docker/docker/hack/make/.go-autogen
